### ISSUE TITLE
How do I initialize a user?

### ISSUE THREAD

**Issue by 128keaton** [coderstephen/slack-client#12]
I've tried multiple different things, like:
`	$user = new User($client, $data['user']);`
but I can't get them to work.

EDIT: the error I receive:
`Slack\ClientObject::__construct() must be of the type array, string given`

**Comment by coderstephen** [comment]
How do you mean, initialize user? The constructor for most of the data classes like `User` aren't meant to be used directly. For example, if you want to get an existing user with the username `slackbot`, you could do something like this:

```php
$client->getUserByName("slackbot")->then(function (User $user) {
    // do something with $user
});
```

**Comment by 128keaton** [comment]
@coderstephen what about a lookup from ID?

**Comment by coderstephen** [comment]
By ID is quite similar:

```php
$client->getUserById("U1234567890")->then(function (User $user) {
    // do something with $user
});
```

See [the API documentation](http://coderstephen.github.io/slack-client/api) for more available methods. The `ApiClient` class is the most interesting one.
