### ISSUE TITLE
How does the looping functionality work?

### ISSUE THREAD

**Issue by 128keaton** [coderstephen/slack-client#13]
I see that there is a loop, is it based off of when a user sends a message in the channel? I'd like to have a function ran when someone inputs a message. Right now, I'm using JS to refresh the div and send a request every minute or so.

**Comment by coderstephen** [comment]
Yes, there is a loop. This Slack client is actually *asynchronous*, meaning that it uses an asynchronous event loop to handle multiple network operations simultaneously. Specifically, the client uses [ReactPHP](http://reactphp.org) at its core to deal with operations.

As a result, everything in the library is pretty much deferred to happen until later, kind of how `setTimeout()` in JS works. You *always* have to run the ReactPHP event loop at the end of your script if you want the code to run properly. For example:

```php
$loop = React\EventLoop\Factory::create();

$client = new Slack\RealTimeClient($loop);
$client->setToken('YOUR-TOKEN-HERE');

// disconnect after first message
$client->on('message', function ($data) use ($client) {
    echo "Someone typed a message: ".$data['text']."\n";
    $client->disconnect();
});

$client->connect()->then(function () {
    echo "Connected!\n";
});

// We are running the ReactPHP event loop with this method call.
$loop->run();
```

**Comment by coderstephen** [comment]
> I'd like to have a function ran when someone inputs a message. Right now, I'm using JS to refresh the div1 and send a request every minute or so.

While that *could* work, it isn't really how the client is meant to be used, or ReactPHP projects in general. The client is designed to be run as a CLI script that acts as a daemon and *continuously* receives events and handles them. Putting the script behind a web server probably won't work that well.

**Comment by 128keaton** [comment]
@coderstephen hmm. Ok. I figured it would be something like that. Is there any library that could handle what I am trying to accomplish? Yours was the only one that came close.

**Comment by coderstephen** [comment]
> Yours was the only one that came close.

Thanks! I made it because the other clients were API incomplete.

If you're looking for a request-response client, I'd check the [PHP community Slack projects page](https://api.slack.com/community#php) for an alternative.
