### ISSUE TITLE
getAuthedUser() not working properly

### ISSUE THREAD

**Issue by notmyrealcode** [coderstephen/slack-client#15]
Hi there, great Slack client, thanks!

There seems to be an issue 

$client->getAuthedUser()->done(function ($user)  {
    //something
});

where $client is the RealTimeClient. It outputs the notice: PHP Notice:  Undefined index: XXXXXXX in /vagrant/dev/slack/vendor/coderstephen/slack-client/src/RealTimeClient.php on line 218

and $user is null. 

Or am I using this incorrectly?

**Comment by coderstephen** [comment]
That is the correct usage of the method. There must be a bug somewhere, because that could only happen if the authenticated user doesn't actually exist, which can't be. I'll see if I can figure out the source of the bug.

**Comment by coderstephen** [comment]
Try installing `dev-master` and see if that fixes the problem.

**Comment by notmyrealcode** [comment]
Hmm, so no notice message any more, but not getting anything back. I'm new to react, so maybe I'm not using it correctly, but here is what I'm testing:

  $client = new Slack\RealTimeClient($loop);
  $client->setToken(SLACK_TOKEN);

    $bot_user = $client->getAuthedUser()->then(function ($user)  {
      print "hello\n";
      print print_r($user);
      print "I am :".$user->getUsername();
      return $user;
     });

**Comment by coderstephen** [comment]
Ah, I see the issue. You need to make sure you call `RealTimeClient::connect()` before you are actually connected and can use the client. Try this:

```php
$client = new Slack\RealTimeClient($loop);
$client->setToken(SLACK_TOKEN);

$client->connect()->then(function () use ($client) {
    $bot_user = $client->getAuthedUser()->then(function ($user)  {
        print "hello\n";
        print "I am :".$user->getUsername();
        return $user;
    });
});
```

**Comment by coderstephen** [comment]
Closing. Please open a new issue if you have any more problems.
