### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by foooooo** [coderstephen/slack-client#6]
>$ composer require coderstephen/slack-client
>Using version ^0.2.0 for coderstephen/slack-client
>./composer.json has been created
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Installation request for coderstephen/slack-client ^0.2.0 -> satisfiable by coderstephen/slack->client[v0.2.0].
>    - coderstephen/slack-client v0.2.0 requires devristo/phpws dev-master -> no matching package found.
>
>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
>
>Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
>
>Installation failed, deleting ./composer.json.

**Comment by coderstephen** [comment]
Unfortunately, slack-client depends on a development version of PHPWS at the moment, so you will need to set the [`minimum-stability`](https://getcomposer.org/doc/04-schema.md#minimum-stability) to `dev` in your composer file beforehand to install the client.

**Comment by vincecore** [comment]
Or manually add phpws as dependency like this: `"devristo/phpws": "dev-master@dev"`
